---
title: "R codes"
format: html
editor: visual
---

## Main analysis (no mmse)

### 1. Mice

```{r}
# mice 
# outcome: tests, not use mmse
setwd ("P:\\yzhang\\whitehall II\\AAIC")
library(tidyverse)
library(mice)
library(miceadds)
# create missing number for each var
mydat <- read_csv("cog_nommse_3011_1st.csv")

# use log_mvpa, add a small random number unif(1,3) to zero mvpa
# add into predictors:
#censoring at wave 7, 9, 11, 12, censor=1, no/disease=0
#outcome at wave 7, 9, 11, 12, disease-1, no/censor=0
set.seed(1234)
miss1 <- mydat %>%
  mutate (mvpa = ifelse(mvpa_calcu = 0, runif(n(), min = 1, max = 3), mvpa_calcu),
          log_mvpa = log(mvpa)) %>%
  mutate (cc = if_else(is.na(cog_imp_nommse), 1, 0),
          disease = if_else(is.na(cog_imp_nommse), 0, cog_imp_nommse))

miss2 <- miss1 %>%
  group_by(id) %>%
  mutate (base_age = age [wave == 5]) %>%
  ungroup %>%
  select (
    wave,
    id,
    base_age,
    male,
    mar_cohab,
    edu,
    income,
    apoe4,
    log_mvpa,
    mind,
    hv_drink,
    current_smk,
    My_SBP,
    MY_BLCHOL,
    MY_GLUC_F,
    My_BMI,
    cvd,
    depress,
    mar_cohab,
    edu,
    income,
    apoe4,
    cc,
    disease
  )

# income and apoe4 have > 2 levels
miss2$income <- factor (miss2$income)
miss2$apoe4 <- factor (miss2$apoe4)

# fixed variables
fixed_var <- c("income", "apoe4")
# time-varying variables
time_varying_var <- c(
  "mar_cohab",
  "cvd",
  "depress",
  "log_mvpa",
  "My GLUC_F",
  "MY_SBP",
  "MY_BLCHOL",
  "MY_BMI",
  "hv_drink",
  "current_smk",
  "mind"
)

# set up imputation models
init <- mice (miss2, maxit = 0, printFlag = F)
imp_method <- init$method

#fixed variable
imp_method ["income"] <- "2lonly.pmm" # for continuous, ordered
imp_method ["apoe4"] <- "2lonly.function" # miceadd package
#time-varying
imp_method [c ("MY_SBP", "MY_BLCHOL", "MY_BMI", "mind")] <- "2l.pan"
imp_method[c("log_mvpa",
             "My_GLUC_F",
             "hv_drink",
             "current_smk",
             "cvd",
             "depress",
             "mar_cohab")] <- "2l.pmm"

imp_pred <- init$predictorMatrix
imp_pred [, "id"] = 0 # not treat id as fixed variable

# set cluster id =-2
imp_pred [c(
  "income",
  "apoe4",
  "MY_SBP",
  "MY_BLCHOL",
  "My BMI",
  "mind",
  "log_mvpa",
  "My_GLUC_F",
  "hv_drink",
  "current_smk",
  "cvd",
  "depress",
  "mar_cohab"
), "id"] = -2

imp_pred[fixed_var, "wave"] <- 0

# no missing
imp_pred [c("id", "base_age", "male", "cc", "disease", "wave"), ] = 0

# order
vis_new <- c(fixed_var, time_varying_var)
imp_mice <- mice(
  data = miss2,
  method = imp_method,
  predictorMatrix = imp_pred,
  m = 50,
  maxit = 20,
  seed = 1,
  imputationFunction = list("apoe4" = "polyreg"),
  cluster_var = "id",
  visitSequence = vis_new
)

saveRDS (imp_mice, file = "mice_data_06_04_2026_nommse.rds")
```

### 2. g-formula

```{r}
library(gformula)

imp_mice <- readRDS ("mice_data_06_04_2026_nommse.rds")
dat_list <- complete(imp_mice, "all")
dat_list_updated <- lapply(dat_list, function(df) {
  df$cog_imp_nommse <- df$disease
  df$cog_imp_nommse [df$cc == 1] <- NA
  # create t0 and censoring
  df <- df %>%
    mutate(t0 = case_when(wave == 5 ~ 0, wave == 7 ~ 1
                          wave == 9 ~ 2, wave == 11 ~ 3))
  return (df)
})

library(data.table)
dat_list_updated <- lapply(dat_list_updated, as.data.table)

library(furrr)
iwalk (dat_list_updated, function (dataset, idx) {
  res <- gformula (
    obs_data = dataset,
    id = "id",
    time_name = "t0",
    time_points = 4,
    outcome_name = "cog_imp_nommse",
    outcome_type = "survival",
    censor_name = "cc",
    
    basecovs = c("base_age", "male", "apoe4", "edu", "income"),
    covnames = c(
      "log_mvpa",
      "mar_cohab",
      "current_smk",
      "hv_drink",
      "My_SBP",
      "MY_BLCHOL",
      "MY_GLUC_F",
      "MY_BMI",
      "cvd",
      "depress",
      "mind"
    ),
    covtypes = c(
      'normal',
      rep("binary", 3),
      rep("normal", 4),
      rep("binary", 2),
      'normal'
    ),
    
    histories = c(lagged),
    histvars = list(
      c(
        "log_mvpa",
        "mar_cohab",
        "current_smk",
        "hv_drink",
        "My_SBP",
        "MY_BLCHOL",
        "MY_GLUC_F",
        "My_BMI",
        "cvd",
        "depress",
        "mind"
      )
    ),
    
    covparams = list(
      covmodels = c(
        log_mvpa ~ as.factor(t0) + base_age + male + as.factor (apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        mar_cohab ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        current_smk ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        hv_drink ~ as.factor(t0) + base_age + male + as. factor (apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        My_SBP ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        My_BLCHOL ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as. factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + Tag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        My_GLUC_F ~ as.factor(to) + base_age + male + as.factor(apoe4) + edu + as. factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        My_BMI ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind++log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        cvd ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          lag1_cvd +
          depress + lag1_depress,
        
        depress ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          lag1_depress,
        
        mind ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + Tag1_current_smk +
          hv_drink + lag1_hv_drink +
          lag1_mind+
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress
      )
    ),
    
    ymodel = "cog_imp_nommse ~ as.factor(t0) + base_age + male + as.factor (apoe4) + edu + as.factor(income) + mar_cohab + current_smk+ hv_drink + mind + log_mvpa + My_SBP + My_BLCHOL+ MY_GLUC_F+ My_BMI+ cvd + depress",
    
    censor_model = "cc ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) + mar_cohab + current_smk+ hv_drink + mind + log_mvpa + My_SBP + My BLCHOL+ My GLUC_F+ My_BMI + cvd + depress",
    
    intervention1.log_mvpa = list(threshold, log(150), Inf),
    
    intervention2.log_mvpa = list(threshold, log(75), Inf),
    
    intervention3.log_mvpa = list(threshold, log(150), Inf),
    intervention3.mind = list(threshold, 8.5, Inf),
    
    intervention4.log_mvpa = list(threshold, log(150), Inf),
    intervention4.current_smk = list(static, rep(0, 4)),
    
    intervention5.log_mvpa = list(threshold, log(150), Inf),
    intervention5.hv_drink = list(static, rep(0, 4)),
    
    intervention6.log_mvpa = list(threshold, log(150), Inf),
    intervention6.mind = list(threshold, 8.5, Inf),
    intervention6.current_smk = list(static, rep(0, 4)),
    
    intervention7.log_mvpa = list(threshold, log(150), Inf),
    intervention7.current_smk = list(static, rep(0, 4)),
    intervention7.hv_drink = list(static, rep(0, 4)),
    
    intervention8.log_mvpa = list(threshold, log(150), Inf),
    intervention8.mind = list(threshold, 8.5, Inf),
    intervention8.current_smk = list(static, rep(0, 4)),
    intervention8.hv_drink = list(static, rep(0, 4)),
    
    intervention9.log_mvpa = list(threshold, log(150), Inf),
    intervention9.My_SBP = list(threshold, -Inf, 129.9),
    
    intervention10.1og_mvpa = list(threshold, log(150), Inf),
    intervention10.My_BLCHOL = list(threshold, -Inf, 6.17),
    
    intervention11.log_mvpa = list(threshold, log(150), Inf),
    intervention11.My_GLUC_F = list(threshold, -Inf, 5.59),
    
    intervention12.log_mvpa = list(threshold, log (150), Inf),
    intervention12.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention13.log_mvpa = list(threshold, log(150), Inf),
    intervention13.My_SBP = list(threshold, -Inf, 129.9),
    intervention13.My_BLCHOL = list(threshold, -Inf, 6.17),
    intervention13.My_GLUC_F = list(threshold, -Inf, 5.59),
    intervention13.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention14.log_mvpa = list(threshold, log (150), Inf),
    intervention14.mind = list(threshold, 8.5, Inf),
    intervention14.current_smk = list(static, rep (0, 4)),
    intervention14.My_SBP = list(threshold, -Inf, 129.9),
    intervention14.My_BLCHOL = list(threshold, -Inf, 6.17),
    intervention14.MY_GLUC_F = list(threshold, -Inf, 5.59),
    intervention14.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention15.log_mvpa = list(threshold, log(150), Inf),
    intervention15.mind = list(threshold, 8.5, Inf),
    intervention15.current_smk = list(static, rep (0, 4)),
    intervention15.hv_drink = list(static, rep(0, 4)),
    intervention15.My_SBP = list(threshold, -Inf, 129.9),
    intervention15.My_BLCHOL = list(threshold, -Inf, 6.17),
    intervention15.My_GLUC_F = list(threshold, -Inf, 5.59),
    intervention15.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention16.mind = list(threshold, 8.5, Inf),
    
    intervention17.current_smk = list(static, rep (0, 4)),
    
    intervention18.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention19.hv_drink = list(static, rep(0, 4)),
    
    nsimul = 10000,
    nsamples = 1000,
    boot_diag = T,
    seed = 1234 + as.numeric(idx),
    parallel = F
  )
  
  saveRDS (res,
           file = paste("update06_04_2026/gformula_nommse/gform_imp_", idx, ".rds"))
  
  rm(res)
  gc()
})
```

### 3. Pool results (Rubin's rules)

```{r}
# pool results for each imputation dataset
file_name <- list.files (path = "P:\\yzhang\\Whitehall II\\AAIC\\update06_04_2026\\gformula_nommse\\",
                         pattern = "gform_imp_.*\\.rds",
                         full.names = T)

all_file <- lapply(file_name, readRDS)

# extract
n_dat <- 50
all_risks <- lapply(1:n_dat, function(i) {
  df <- all_file[[i]]$result %>%
    select (`k`,
            `Interv.`,
            `g_form risk`,
            `Risk ratio`,
            `Aver % Intervened On`) %>%
    mutate (imp_id = i)
  return(df)
}) %>%
  bind_rows()

# pooled rr and between-imputation variance
pooled_time_risks <- all_risks %>%
  group_by(k, Interv.) %>%
  summarize(
    pooled_risk_obs = mean (`g_form risk`),
    pooled_log_rr_obs = mean (log(`Risk ratio`), na.rm = T),
    pooled_rr_obs = exp(pooled_log_rr_obs),
    pooled_intv_obs = mean (`Aver % Intervened On`, na.rm = T),
    Bvar_log_rr_obs = var(log(`Risk ratio`), na.rm = T),
    .groups = 'drop'
  )

pooled_time_risks


## CI for RR (bootstrap)
boot <- lapply(1:n_dat, function(i) {
  df <- all_file[[i]]$bootests %>%
    filter(!is.na (`Natural course`)) %>%
    mutate(across(
      starts_with ("Intervention"),
      ~ log(.x / `Natural course`),
      .names = "log_rr{. col}"
    )) %>%
    rename_with( ~ str_replace(., "Intervention ", ""),
                 contains ("Intervention")) %>%
    group_by(t0) %>%
    # for each impuated data, calclaute variance (log RR)
    summarise (across (starts_with("log_rr"), \(x) var (x), .names = "w_i_{.co]}")) %>%
    ungroup() %>%
    pivot_longer (
      cols = starts_with("w_i_"),
      names_to = "Interv.",
      names_prefix = "w_i_log_rr",
      names_transform = as.numeric,
      values_to = "var_log_rr"
    ) %>%
    mutate(imp_id = i, k = t0)
  
  return (df)
}) %>%
  bind_rows()


boot1 <- boot %>%
  group_by(k, Interv.) %>%
  # within-imputation variance as the mean of 50 impuated variance
  summarize (Wvar_log_rr_boot = mean (var_log_rr)) %>%
  ungroup()

boot1

pooled_result <- left_join(pooled_time_risks, boot1)
pooled_result

pooled_result <- pooled_result %>%
  mutate(
    Tvar_log_rr = Bvar_log_rr_obs + Bvar_log_rr_obs / n_dat + Wvar_log_rr_boot,
    Tse_log_rr = sqrt(Tvar_log_rr),
    low_rr_boot = exp (pooled_log_rr_obs - 1.96 * Tse_log_rr),
    upp_rr_boot = exp(pooled_log_rr_obs + 1.96 * Tse_log_rr)
  )
```

## Sensitivity analysis (with mmse)

### 1.Mice

```{r}
# mice
# outcome: tests, not use mmse
setwd ("P:\\yzhang\\whitehall II\\AAIC")
library(tidyverse)
library(mice)
library(miceadds)
# create missing number for each var
mydat <- read_csv("cog_imp_3032_1st.csv")

# use log_mvpa, add a small random number unif(1,3) to zero mvpa
# add into predictors:
#censoring at wave 7, 9, 11, 12, censor=1, no/disease=0
#outcome at wave 7, 9, 11, 12, disease-1, no/censor=0
set.seed(1234)
miss1 <- mydat %>%
  mutate (mvpa = ifelse(mvpa_calcu = 0, runif(n(), min = 1, max = 3), mvpa_calcu),
          log_mvpa = log(mvpa)) %>%
  mutate (cc = if_else(is.na(cog_imp_nommse), 1, 0),
          disease = if_else(is.na(cog_imp_nommse), 0, cog_imp_nommse))

miss2 <- miss1 %>%
  group_by(id) %>%
  mutate (base_age = age [wave == 5]) %>%
  ungroup %>%
  select (
    wave,
    id,
    base_age,
    male,
    mar_cohab,
    edu,
    income,
    apoe4,
    log_mvpa,
    mind,
    hv_drink,
    current_smk,
    My_SBP,
    MY_BLCHOL,
    MY_GLUC_F,
    My_BMI,
    cvd,
    depress,
    mar_cohab,
    edu,
    income,
    apoe4,
    cc,
    disease
  )

# income and apoe4 have > 2 levels
miss2$income <- factor(miss2$income)
miss2$apoe4 <- factor(miss2$apoe4)

# fixed variables
fixed_var <- c("income", "apoe4")
# time-varying variables
time_varying_var <- c(
  "mar_cohab",
  "cvd",
  "depress",
  "log_mvpa",
  "My GLUC_F",
  "MY_SBP",
  "MY_BLCHOL",
  "MY_BMI",
  "hv_drink",
  "current_smk",
  "mind"
)

# set up imputation models
init <- mice (miss2, maxit = 0, printFlag = F)
imp_method <- init$method

#fixed variable
imp_method ["income"] <- "2lonly.pmm" # for continuous, ordered
imp_method["edu"] <- "2lonly.norm"
imp_method ["apoe4"] <- "2lonly.function" # miceadd package
#time-varying
imp_method [c ("MY_SBP", "MY_BLCHOL", "MY_BMI", "mind")] <- "2l.pan"
imp_method[c("log_mvpa",
             "My_GLUC_F",
             "hv_drink",
             "current_smk",
             "cvd",
             "depress",
             "mar_cohab")] <- "2l.pmm"

imp_pred <- init$predictorMatrix
imp_pred [, "id"] = 0 # not treat id as fixed variable

# set cluster id =-2
imp_pred [c(
  "income",
  "apoe4",
  "MY_SBP",
  "MY_BLCHOL",
  "My BMI",
  "mind",
  "log_mvpa",
  "My_GLUC_F",
  "hv_drink",
  "current_smk",
  "cvd",
  "depress",
  "mar_cohab"
), "id"] = -2

imp_pred[fixed_var, "wave"] <- 0

# no missing
imp_pred [c("id", "base_age", "male", "cc", "disease", "wave"), ] = 0

# order
vis_new <- c(fixed_var, time_varying_var)

# post-processing
my_post <- setNames (rep("", ncol (miss2)), names (miss2))
my_post["edu"] <- "imp$edu <- round (imp$edu)"

imp_mice <- mice (
  data = miss2,
  method = imp_method,
  predictorMatrix = imp_pred,
  m = 50,
  maxit = 20,
  seed = 1,
  imputationFunction = list("apoe4"  = "polyreg"),
  cluster_var = "id",
  visitSequence =  vis_new,
  post = my_post
)

saveRDS(imp_mice, file = "mice_data_06_04_2026.rds")
	
```

### 2. g-formula

```{r}
library(tidyverse)
library(gformula)

imp_mice <- readRDS ("mice_data_06_04_2026.rds")
dat_list <- complete(imp_mice, "all")

dat_list_updated <- lapply(dat_list, function(df) {
  df$cog_imp_nommse <- df$disease
  df$cog_imp_nommse [df$cc == 1] <- NA
  # create t0 and censoring
  df <- df %>%
    mutate(t0 = case_when(wave == 5 ~ 0, wave == 7 ~ 1
                          wave == 9 ~ 2, wave == 11 ~ 3))
  return (df)
})

library(data.table)
dat_list_updated <- lapply(dat_list_updated, as.data.table)

library(furrr)
iwalk (dat_list_updated, function (dataset, idx) {
  res <- gformula (
    obs_data = dataset,
    id = "id",
    time_name = "t0",
    time_points = 4,
    outcome_name = "cog_imp",
    outcome_type = "survival",
    censor_name = "cc",
    
    basecovs = c("base_age", "male", "apoe4", "edu", "income"),
    covnames = c(
      "log_mvpa",
      "mar_cohab",
      "current_smk",
      "hv_drink",
      "My_SBP",
      "MY_BLCHOL",
      "MY_GLUC_F",
      "MY_BMI",
      "cvd",
      "depress",
      "mind"
    ),
    covtypes = c(
      'normal',
      rep("binary", 3),
      rep("normal", 4),
      rep("binary", 2),
      'normal'
    ),
    
    histories = c(lagged),
    histvars = list(
      c(
        "log_mvpa",
        "mar_cohab",
        "current_smk",
        "hv_drink",
        "My_SBP",
        "MY_BLCHOL",
        "MY_GLUC_F",
        "My_BMI",
        "cvd",
        "depress",
        "mind"
      )
    ),
    
    covparams = list(
      covmodels = c(
        log_mvpa ~ as.factor(t0) + base_age + male + as.factor (apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        mar_cohab ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        current_smk ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        hv_drink ~ as.factor(t0) + base_age + male + as. factor (apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        My_SBP ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        My_BLCHOL ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as. factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + Tag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        My_GLUC_F ~ as.factor(to) + base_age + male + as.factor(apoe4) + edu + as. factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        My_BMI ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind++log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress,
        
        cvd ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          lag1_cvd +
          depress + lag1_depress,
        
        depress ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + lag1_current_smk +
          hv_drink + lag1_hv_drink +
          mind + lag1_mind +
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          lag1_depress,
        
        mind ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) +
          mar_cohab + lag1_mar_cohab +
          current_smk + Tag1_current_smk +
          hv_drink + lag1_hv_drink +
          lag1_mind+
          log_mvpa + lag1_log_mvpa +
          My_SBP + lag1_My_SBP +
          My_BLCHOL + lag1_My_BLCHOL +
          My_GLUC_F + lag1_My_GLUC_F +
          My_BMI + lag1_My_BMI +
          cvd + lag1_cvd +
          depress + lag1_depress
      )
    ),
    
    ymodel = "cog_imp ~ as.factor(t0) + base_age + male + as.factor (apoe4) + edu + as.factor(income) + mar_cohab + current_smk+ hv_drink + mind + log_mvpa + My_SBP + My_BLCHOL+ MY_GLUC_F+ My_BMI+ cvd + depress",
    
    censor_model = "cc ~ as.factor(t0) + base_age + male + as.factor(apoe4) + edu + as.factor(income) + mar_cohab + current_smk+ hv_drink + mind + log_mvpa + My_SBP + My BLCHOL+ My GLUC_F+ My_BMI + cvd + depress",
    
    intervention1.log_mvpa = list(threshold, log(150), Inf),
    
    intervention2.log_mvpa = list(threshold, log(75), Inf),
    
    intervention3.log_mvpa = list(threshold, log(150), Inf),
    intervention3.mind = list(threshold, 8.5, Inf),
    
    intervention4.log_mvpa = list(threshold, log(150), Inf),
    intervention4.current_smk = list(static, rep(0, 4)),
    
    intervention5.log_mvpa = list(threshold, log(150), Inf),
    intervention5.hv_drink = list(static, rep(0, 4)),
    
    intervention6.log_mvpa = list(threshold, log(150), Inf),
    intervention6.mind = list(threshold, 8.5, Inf),
    intervention6.current_smk = list(static, rep(0, 4)),
    
    intervention7.log_mvpa = list(threshold, log(150), Inf),
    intervention7.current_smk = list(static, rep(0, 4)),
    intervention7.hv_drink = list(static, rep(0, 4)),
    
    intervention8.log_mvpa = list(threshold, log(150), Inf),
    intervention8.mind = list(threshold, 8.5, Inf),
    intervention8.current_smk = list(static, rep(0, 4)),
    intervention8.hv_drink = list(static, rep(0, 4)),
    
    intervention9.log_mvpa = list(threshold, log(150), Inf),
    intervention9.My_SBP = list(threshold, -Inf, 129.9),
    
    intervention10.1og_mvpa = list(threshold, log(150), Inf),
    intervention10.My_BLCHOL = list(threshold, -Inf, 6.17),
    
    intervention11.log_mvpa = list(threshold, log(150), Inf),
    intervention11.My_GLUC_F = list(threshold, -Inf, 5.59),
    
    intervention12.log_mvpa = list(threshold, log (150), Inf),
    intervention12.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention13.log_mvpa = list(threshold, log(150), Inf),
    intervention13.My_SBP = list(threshold, -Inf, 129.9),
    intervention13.My_BLCHOL = list(threshold, -Inf, 6.17),
    intervention13.My_GLUC_F = list(threshold, -Inf, 5.59),
    intervention13.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention14.log_mvpa = list(threshold, log (150), Inf),
    intervention14.mind = list(threshold, 8.5, Inf),
    intervention14.current_smk = list(static, rep (0, 4)),
    intervention14.My_SBP = list(threshold, -Inf, 129.9),
    intervention14.My_BLCHOL = list(threshold, -Inf, 6.17),
    intervention14.MY_GLUC_F = list(threshold, -Inf, 5.59),
    intervention14.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention15.log_mvpa = list(threshold, log(150), Inf),
    intervention15.mind = list(threshold, 8.5, Inf),
    intervention15.current_smk = list(static, rep (0, 4)),
    intervention15.hv_drink = list(static, rep(0, 4)),
    intervention15.My_SBP = list(threshold, -Inf, 129.9),
    intervention15.My_BLCHOL = list(threshold, -Inf, 6.17),
    intervention15.My_GLUC_F = list(threshold, -Inf, 5.59),
    intervention15.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention16.mind = list(threshold, 8.5, Inf),
    
    intervention17.current_smk = list(static, rep (0, 4)),
    
    intervention18.My_BMI = list(threshold, 18.5, 24.9),
    
    intervention19.hv_drink = list(static, rep(0, 4)),
    
    nsimul = 10000,
    nsamples = 1000,
    boot_diag = T,
    seed = 1234 + as.numeric(idx),
    parallel = F
  )
  
  saveRDS (res,
           file = paste("update06_04_2026/gformula/gform_imp_", idx, ".rds"))
  
  rm(res)
  gc()
})
```

